bash: Ditch the `onoe` function
It's not portable across shells, and unlike bash, most shells don't have
a facility for making shell functions available in scripts. I shouldn't
use it in scripts.

diff --git a/bin/.local/bin/whither b/bin/.local/bin/whither
--- a/bin/.local/bin/whither
+++ b/bin/.local/bin/whither
@@ -10,7 +10,7 @@ else
   if command -v $1 &>/dev/null; then
     type $1
   else
-    onoe "$0: $1: command not found"
+    echo "$0: $1: command not found" >&2
     exit 1
   fi
 fi
